server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
            - Path=/api/auth/**
        - id: task-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/tasks/**
        - id: analytics-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/analytics/**
        - id: ai-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/ai/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
