spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/taskservice}
server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
